# Generated by Django 5.2.12 on 2026-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
